---

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
     project_dir : "./"

  tasks:

  - name: "terraform apply"
    community.general.terraform:
      project_path: "{{ project_dir }}"
      complex_vars: true
      variables:
        name: "{{ name_bucket }}"
        project: "{{ name_project }}"
        location: "{{ name_location }}"
        storageclass: "{{ name_storageclass }}"
      state: present
      force_init: true
    register: apply_result
    tags:
     - apply

